port: 53
host:
  www.example.com: 1.1.1.1
upstream:
  - name: cn-dns
    url: 114.114.114.114:53
    rule:
      - .cn
      - :gfwlist
      - :remote:https://www.example.com/raw.txt
  - name: doh
    url: https://cloudflare-dns.com/dns-query
    config:
      bootstrap: 114.114.114.114