port: 53
host:
  www.example.com: 1.1.1.1
cache:
  ttl: 10s
upstream:
  - name: cn-dns
    url: 114.114.114.114:53
    rule:
      - cn
      - qq.com
      - wechat.com
      - include:v2-rule.txt
  - name: doh
    url: https://cloudflare-dns.com/dns-query
    config:
      bootstrap:
        - 114.114.114.114
    rule:
      - include:gfwlist-rule.txt
  - name: google-ecs
    url: https://dns.google/dns-query
    config:
      clientIP: 59.172.144.144
      bootstrap:
        - 114.114.114.114